services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:8080"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - guacamole1
      - guacamole2
    networks:
      - guacnetwork

  guacamole1:
    image: guacamole/guacamole:latest
    container_name: guacamole1
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_HOSTNAME: postgres
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: your_password
      GUACAMOLE_HOME: /home/guacamole/.guacamole
    user: "0:0"
    volumes:
      - ./my-theme-extension/guac-theme.jar:/home/guacamole/.guacamole/extensions/guac-theme.jar
    depends_on:
      - guacd
      - postgres
    networks:
      - guacnetwork

  guacamole2:
    image: guacamole/guacamole:latest
    container_name: guacamole2
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_HOSTNAME: postgres
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: your_password
      GUACAMOLE_HOME: /home/guacamole/.guacamole
    user: "0:0"
    volumes:
      - ./my-theme-extension/guac-theme.jar:/home/guacamole/.guacamole/extensions/guac-theme.jar
    depends_on:
      - guacd
      - postgres
    networks:
      - guacnetwork

  guacd:
    image: guacamole/guacd:latest
    container_name: guacd
    networks:
      - guacnetwork

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: your_password
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - guacnetwork
networks:
  guacnetwork:
    driver: bridge
